version: '3'
services:
  mongodb:
    image: mongo:8.0.10
    container_name: book-service-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"